# Generated by Django 4.0.4 on 2022-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_auto', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('text_about_auto', models.TextField(verbose_name='Описание автомобиля')),
                ('photo', models.ImageField(upload_to='photos/%Y/%n/%d/', verbose_name='Фото авто')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог авто',
            },
        ),
    ]
