# Generated by Django 4.0.4 on 2022-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_on_test_drive',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
