# Generated by Django 4.0.4 on 2022-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Drive', '0002_alter_register_on_test_drive_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_on_test_drive',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
