# Generated by Django 4.0.4 on 2022-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Drive', '0003_alter_register_on_test_drive_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_on_test_drive',
            name='car',
            field=models.CharField(default='', max_length=30, verbose_name='Авто на тест'),
        ),
    ]
