# Generated by Django 4.0.4 on 2022-06-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_on_test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('car', models.CharField(default='', max_length=30, verbose_name='Авто')),
                ('text', models.TextField(verbose_name='Причина')),
                ('data', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Регистриция на ТО',
                'verbose_name_plural': 'Регистриция на ТО',
            },
        ),
    ]
